export const prompts: Prompt[] = [
	{
		type: "banner",
		prompt:
			"Create a playful banner message that lets visitors know all text is being generated by AI. Emphasize that they should hang tight because the content will be worth the wait. Mention it's powered by Google Gemini with a humorous twist.",
	},
	{
		type: "aboutme",
		prompt:
			"Write a fun and engaging biography of Sunehildeep Singh. Highlight his educational background, professional experiences, and passions with a touch of humor. Make it clear who he is, but keep it light and relatable. Describe Sunehildeep Singh's life goals and aspirations with a casual, conversational tone. Outline his vision for his career and personal life in a way that feels genuine and a bit cheeky.",
	},

	{
		type: "myskills",
		prompt:
			"List Sunehildeep Singh's skills in a structured way. Showcase his expertise with bullet points. Keep it concise and engaging.",
	},
	{
		type: "contactme",
		prompt:
			"Provide contact information for Sunehildeep Singh with a friendly and approachable tone. Make it easy to find and use, and add a touch of personality to invite potential collaborators or inquiries.",
	},
];
