import React from "react";
import "../styles/cyberpunk.css";
import { Link } from "react-scroll";
import ReactMarkdown from "react-markdown";

const CyberpunkBanner = ({ text }) => {
	return (
		<div className="cyberpunk-banner">
			<video className="bg-video" autoPlay loop muted>
				<source src={"images/bg2.mp4"} type="video/mp4" />
			</video>
			<div className="glitch-container">
				<div className="glitch-overlay"></div>
				<h1 className="glitch-text">Welcome to my Portfolio</h1>
				<p className="glitch-subtitle">
					<ReactMarkdown>{text}</ReactMarkdown>
				</p>
				<h5>
					NOTE: All the text is being generated by AI in real-time. Please wait
					for a few seconds for the text to load.
				</h5>
				<Link
					className="glitch-button"
					to="about"
					smooth={true}
					duration={500}
					offset={-100}
				>
					Learn More
				</Link>
			</div>
		</div>
	);
};

export default CyberpunkBanner;
