name: deploy-next (Deploy staging environments to Github Actions)

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy-next, deploy-staging]

jobs:
  next:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Update to latest release candidate
        run: yarn update-next
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
      - name: Build project
        run: yarn build
      - name: Export project
        run: yarn export
      - name: Deploying to Github Pages
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}

          git checkout -- package.json
          git checkout -- yarn.lock
          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          git update-ref -d refs/remotes/origin/gh-pages
          git pull origin gh-pages

          rm -rf next
          mkdir -p next
          cp -rf out/* next

          git add -f next
          git commit -m "chore(deploy): deploy next to GitHub Pages"
          git push origin gh-pages
